language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - ninja
            - meson
            - python3
      install: "meson Build"
      script: "ninja -C Build/"

    - os: linux
      addons:
        apt:
          packages:
            - ninja
            - python3
            - python3-pip
            - python3-setuptools
      install:
        - pip3 install meson
        - meson Build
      script: "ninja -C Build/"

    - os: windows
      addons:
        choco:
          packages:
            - ninja
            - python
      install:
        - pip install meson
        - meson Build
      script: "ninja -C Build"
git:
  submodules: true