language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - ninja
            - meson
            - python3
      install: "meson Build"
      script: "ninja -C Build/"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - python3
            - python3-pip
            - python3-setuptools
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      install:
        - pip3 install meson
        - meson Build
      script: "ninja -C Build/"

    - os: windows
      addons:
        choco:
          packages:
            - ninja
            - pip
      install:
        - python -m pip install meson
        - meson Build
      script: "ninja -C Build"

before_install:
  - eval "${MATRIX_EVAL}"

git:
  depth: 1
  submodules: true