manifest = "1790d6b5d549998ce6273dc9e227ea7acb97e2aefcf99e5e5a578c4abd542b83"

[[dependency]]
package = "github.com/apache-hb/ctulib"
target = "//:CthulhuCore"

[[dependency]]
package = "github.com/apache-hb/ctulib"
target = "//:CthulhuFileSystem"

[lock."github.com/apache-hb/ctulib"]
versions = [ "branch=master" ]
revision = "3541a005f810e2b6e3a087d165606c120a04aaf4"
